# Day 22

# Playbook - list of ansible tasks

- name: Ping the server
  hosts: web
  tasks:
    - name: ping the server
      ansible.builtin.ping:

- name: Ping the server
  hosts: local
  tasks:
    - name: ping the server
      ansible.builtin.ping:


# to run this playbook for both hosts web and local:
# ansible-playbook -i inventory.ini -e ansible_user=ec2-user -e ansible_password=DevOps321 01_playbook.yaml

# ansible-playbook -i inventory.ini -e ansible_user=ec2-user -e ansible_password=DevOps321 01_playbook.yaml --limit web -> to run hosts in web group

- name: Ping the server
  hosts: localhost
  # connection: local
  tasks:
    - name: ping the server
      ansible.builtin.ping:


# ansible-playbook 01_playbook.yaml or ansible-playbook -i localhost, 01_playbook.yaml
# means â†’ run directly on the same machine.