# Day 22

# Playbook - list of ansible tasks

- name: Ping the server
  hosts: web
  tasks:
    - name: ping the server
      ansible.builtin.ping:


# to run this playbook:
# ansible-playbook -i inventory.ini -e ansible_user=ec2-user -e ansible_password=DevOps321 01_playbook.yaml