# Day 22

# Multiple plays in a playbook
- name: Hello World Play 1
  hosts: web
  tasks:
    - name: print hello world 1
      ansible.builtin.debug:
        msg: "Hello World 1"

 
- name: Hello World Play 2
  hosts: local
  connection: local
  tasks:
    - name: print hello world 2
      ansible.builtin.debug:
        msg: "Hello World 2"


# ansible-playbook -i localhost, 02_playbook.yaml