# Day 22

# to get vars from inventory

- name: print username and password
  hosts: local
  connection: local

  tasks:
    - name: print info
      ansible.builtin.debug:
        msg: "Course is {{course}}"