# Day 22

# to get vars from inventory
- name: get vars from inventory
  hosts: local
  connection: local

  tasks:
    - name: print info
      ansible.builtin.debug:
        msg: "Course is {{course}}"