# Day 23

- name: conditions
  hosts: local
  connection: local
  vars:
    sessions_no: 7
  tasks:
    - name: check if ansible is more than 5 sessions
      ansible.builtin.debug:
        msg: "yes it is live"
      when: sessions_no > 5
  