# Day 23

- name: conditions
  hosts: local
  connection: local
  vars:
    is_live: false
  tasks:
    - name: check live or not
      ansible.builtin.debug:
        msg: "yes it is live"
      when: is_live


# skips if its false.