# Day 23

- name: gathering facts
  hosts: local
  connection: local
  tasks:
    - name: print facts
      ansible.builtin.debug:
        msg: "{{ ansible_facts }}"

  tasks:
    - name: check redhat or not
      ansible.builtin.debug:
        msg: "yes it is redhat"
      when: ansible_facts.os_family == "RedHat"
  

  tasks:
    - name: check debian or not
      ansible.builtin.debug:
        msg: "yes it is debian"
      when: ansible_facts.os_family == "Debian"
  