# Day 23

- name: loops
  hosts: local
  connection: local
  tasks:
    - name: print names
      ansible.builtin.debug:
        msg: "Hello {{ item }}" # item is reserved keyword
      loop:
        - QA1
        - QA2
        - QA3